language: go
sudo: true
go:
  - 1.11.x
  - tip

before_install:
  - sudo apt-get install git
  - sudo git clone https://github.com/emersion/go-message.git
  - go get -t -v ./...

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
